# periodicidad de ejecucion en segundos por defecto
ciclo_simulacion_predeterminado: 20

# cantidad de archivos generados en cada ejecucion
cantidad_archivos_generados:
  - minimo: 1
  - maximo: 100

# formato de la fecha utilizado en los archivos generados
formato_fecha_archivo: "%d%m%Y%H%M%S"

# lista de misiones a analizar
misiones:
  - ORBONE: OrbitOne
  - CLNM: ColonyMoon
  - TMRS: VacMars
  - GALXONE: GalaxyTwo
  - UNKN: unknown

# lista de dispositivos a analizar
dispositivos:
  - satelites
  - naves
  - trajes_espaciales
  - vehiculos_espaciales

# estados posibles para cada dispositivo
estados_dispositivo:
  - excellent
  - good
  - warning
  - faulty
  - killed
  - unknown

# formato de la fecha en los logs
formato_fecha_log: "%d-%m-%Y %H:%M:%S"

# formato del contenido en los logs
formato_contenido_log: "%(asctime)s\t%(levelname)s\t%(message)s"
